# NoPlaceLike Cloud - Free to use for all :)
#
# Deployment Pipeline for Demo Project

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: Location
    value: "westeurope"
  - name: ParameterFileLocation
    value: '$(Build.SourcesDirectory)/parameters/main.parameters.json'

steps:
- task: UniversalPackages@0
  displayName: Get Module VM
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)/modules'
    feedsToUse: 'internal'
    vstsFeed: '8a164210-c64e-459d-a85d-9ff86e22d648/0b56d169-f106-4a60-92bb-1a720c1cb848'
    vstsFeedPackage: 'b72c0ef4-5336-4f11-aa01-a46bd9783579'
    vstsPackageVersion: '0.0.1'

- task: UniversalPackages@0
  displayName: Get Module VNET
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)/modules'
    feedsToUse: 'internal'
    vstsFeed: '8a164210-c64e-459d-a85d-9ff86e22d648/0b56d169-f106-4a60-92bb-1a720c1cb848'
    vstsFeedPackage: '78d1370e-d2ed-466d-ae5c-3f72930da54d'
    vstsPackageVersion: '0.0.1'
- task: AzurePowerShell@5
  displayName: Deploy bicep with JSON parameter file
  inputs:
    azureSubscription: 'SP - Axians Tech - VSE BEFL' ## Fill here your Service Connection
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      
      New-AzSubscriptionDeployment -Location $(Location) -TemplateFile $(Build.SourcesDirectory)/main.bicep -TemplateParameterFile $(ParameterFileLocation)