# NoPlaceLike Cloud - Free to use for all :)
#
# Deployment Pipeline for Demo Project

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: Location
    value: "westeurope"
  - name: ParameterFileLocation
    value: '$(Build.SourcesDirectory)/parameters/main.parameters.json'

steps:
- task: AzurePowerShell@5
  displayName: Deploy bicep with JSON parameter file
  inputs:
    azureSubscription: '' ## Fill here your Service Connection
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      
      New-AzSubscriptionDeployment -Location $(Location) -TemplateFile $(Build.SourcesDirectory)/main.bicep -TemplateParameterFile $(ParameterFileLocation)